# Generated by Django 5.2.12 on 2026-03-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='Priority')),
                ('energy_burned_import_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Energy Burned Import Multiplier')),
            ],
            options={
                'verbose_name': 'Integration source',
                'ordering': ['priority'],
                'get_latest_by': 'priority',
            },
        ),
    ]