# Generated by Django 5.2.12 on 2026-03-18 23:55

from django.db import migrations, models

def create_sources(apps, schema_editor):
    IntegrationSource = apps.get_model(
        "thirdparty_integrations",
        "IntegrationSource"
    )

    IntegrationSource.objects.get_or_create(
        name="health_connect",
        display_name="Health Connect",
        priority=1
    )

    IntegrationSource.objects.get_or_create(
        name="polar",
        display_name="Polar",
        priority=2
    )

class Migration(migrations.Migration):

    dependencies = [
        ('thirdparty_integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsource',
            name='display_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Display Name'),
        ),
        migrations.AddField(
            model_name='integrationsource',
            name='name',
            field=models.CharField(default='Source', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.RunPython(create_sources)
    ]